framework:
    secret: '%env(APP_SECRET)%'
    csrf_protection: true # Active la protection CSRF
    session:
        handler_id: null   # Utilise le gestionnaire par défaut pour les sessions
    #esi: true
    #fragments: true

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
