security:
    # Configuration des algorithmes de hachage pour les mots de passe
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    # Configuration des fournisseurs d'utilisateurs
    providers:
        users_in_database:
            entity:
                class: App\Entity\User # Classe de l'entité User
                property: email        # Propriété utilisée pour l'identification

    # Configuration des pare-feux (firewalls)
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: users_in_database
            form_login:
                login_path: app_login   # Route pour afficher le formulaire de connexion
                check_path: app_login   # Route pour vérifier les identifiants
            logout:
                path: app_logout        # Route pour la déconnexion
                target: app_home        # Page vers laquelle rediriger après déconnexion

    # Contrôle d'accès global
    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/profile, roles: ROLE_USER }
        - { path: ^/account, roles: ROLE_USER }

when@test:
    security:
        password_hashers:
            # Simplification du coût des hashages pour les tests
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4       # Valeur minimale pour bcrypt
                time_cost: 3  # Valeur minimale pour argon2
                memory_cost: 10
