security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'


    providers:
        users_in_database:
            entity:
                class: App\Entity\User 
                property: email        

    # Configuration des pare-feux (firewalls)
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/  
            security: false

        main:
            lazy: true
            provider: users_in_database

            custom_authenticators:
                - App\Security\LoginAuthenticator 

            entry_point: App\Security\LoginAuthenticator 

            logout:
                path: app_logout
                target: app_home

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/profile, roles: ROLE_USER }
        - { path: ^/account, roles: ROLE_USER }

when@test:
    security:
        password_hashers:

            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10

services:
    App\Security\LoginAuthenticator:
        alias: 'debug.App\Security\LoginAuthenticator.inner'
        public: true
    App\Controller\ProfileController:
        arguments:
            $authenticator: '@App\Security\LoginAuthenticator'    

    App\Security\LoginAuthenticator.inner:
        alias: App\Security\LoginAuthenticator